name: 'Terraform Activities'
description: 'Provide SHELL-LIKE Terraform Services'
inputs:
  github_workspace:
    description: The base url of the repository
    required: yes
  deployment_type:
    description: Valid values are 'apps' and 'environments'
    required: yes
  github_user:
    description: The github user for xterrafile
    required: yes
  github_token:
    description: The SSO envabled github token for the github_user
    required: yes
  aws_profile:
    description: The name of the AWS Profile to use
    required: yes
  aws_region:
    description: The region for the deployment
    required: yes
  aws_access_key:
    description: The AWS Access key for the deployment
    required: yes
  aws_secret_key:
    description: The AWS Secret Access key for the deploment
    required: yes
  k8s_env:
    description: The deployment environment.  Valid values are 'dev', 'qa', 'stage-primary', 'stage-secondary', 'prod-primary', and 'prod-secondary'
    required: yes
  execute_command:
    description: The command to execute 
    required: yes

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_workspace }}

